"""Ensure PolicyDocument has chunk_count, status, error_message

Revision ID: 42958f492a3d
Revises: a30074c73f3b
Create Date: 2025-04-13 00:55:47.125284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42958f492a3d'
down_revision = 'a30074c73f3b'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns with server_default for existing rows
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_count', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default="Pending"))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # Remove server_default if desired (optional, keeps model clean)
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.alter_column('chunk_count', server_default=None)
        batch_op.alter_column('status', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')
        batch_op.drop_column('chunk_count')

    # ### end Alembic commands ###
