"""Add show_on_schedule to Employee model

Revision ID: 5e1f8fc8526e
Revises: d5da9874c379
Create Date: 2025-03-30 23:22:26.908375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1f8fc8526e'
down_revision = 'd5da9874c379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on_schedule', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('show_on_schedule')

    # ### end Alembic commands ###
