"""Add cell_text to Shift model

Revision ID: 8110a44eb508
Revises: 00d0648ea832
Create Date: 2025-03-31 05:22:37.159725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8110a44eb508'
down_revision = '00d0648ea832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cell_text', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_column('cell_text')

    # ### end Alembic commands ###
