"""Add Feedback table and Policy embedding column

Revision ID: e49b44b2c29c
Revises: 84f23f91aff3
Create Date: 2025-04-05 14:58:56.260916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e49b44b2c29c'
down_revision = '84f23f91aff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('embedding', sa.PickleType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('preferred_shifts',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('preferred_days',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('days_off',
               existing_type=postgresql.ARRAY(sa.DATE()),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('days_off',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.DATE()),
               existing_nullable=True)
        batch_op.alter_column('preferred_days',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
        batch_op.alter_column('preferred_shifts',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)

    op.drop_table('feedback')
    op.drop_table('policies')
    # ### end Alembic commands ###
